package com.example.android_app.utils

import android.text.SpannableStringBuilder
import kotlin.math.sign

// Khai báo các loại ngôn ngữ
enum class AppLanguage { VI, EN }

// Định nghĩa khuôn mẫu các câu chữ trong App
data class AppStrings(
    val welcome: String,
    val login: String,
    val signUp: String,
    val fullName: String,
    val username: String,
    val password: String,
    val temp: String,
    val lit: String,
    val devices: String,
    val devicesIn: String,
    val logout: String,
    val settings: String,
    val changePass: String,
    val language: String,
    val room: String,
    val roomKitchen: String,
    val roomLiving: String,
    val roomBed: String,
    val roomBath: String,
    val Garden: String,
    val fan: String,
    val led: String,
    val warning: String,
    val loginAsk: String,
    val signUpAsk: String,
    val sun: String,
    val clear: String,
    val profileAva: String,
    val warningHistory: String,
    val changeAva: String,
    val PicFrom: String,
    val lib: String,
    val cam: String,
    val ava: String,
    val profile: String,
    val newPass: String,
    val oldPass: String,
    val errorPass: String,
    val updatePass: String,
    val save: String,
    val security: String,
    val sysSetting: String,
    val themes: String,
    val current: String,
    val interf: String,
    val selectThemes: String ,
    val Light: String,
    val Dark: String,
    val Sys: String,
    val presets: String,
    val createPreset: String,
    val editPreset: String,
    val deviceNameDefault: String, // Tên mặc định
    val color: String,
    val speed: String,
    val brightness: String,
    val osc: String, // Chế độ quay
    val track: String,
    val saveSuccess: String,
    val enterPresetName: String,
    val on: String,
    val off: String,
    val addDevice: String,
    val addFan: String,
    val addLight: String,
    val addDeviceAsk: String,
    val rename: String,
    val popular: String,
    val home: String,
    val weahther: String,
    val activity: String,
    val other: String,
)

// Dữ liệu Tiếng Việt
val VietnameseStrings = AppStrings(
    welcome = "Chào mừng về nhà,",
    login = "Đăng nhập",
    signUp = "Đăng ký",
    fullName = "Họ & Tên",
    username = "Tên đăng nhập",
    password = "Mật khẩu",
    temp = "Nhiệt độ",
    lit = "Ánh sáng",
    devices = "Thiết bị",
    devicesIn = "Thiết bị trong ",
    logout = "Đăng xuất",
    settings = "Cài đặt hệ thống",
    changePass = "Đổi mật khẩu",
    language = "Ngôn ngữ",
    room = "Phòng",
    roomKitchen = "Nhà bếp",
    roomLiving = "Phòng khách",
    roomBed = "Phòng ngủ",
    roomBath = "Phòng vệ sinh",
    Garden = "Sân vườn",
    fan = "Quạt",
    led = "Đèn LED",
    warning = "Cảnh báo an ninh!",
    loginAsk = "Đã có tài khoản? Đăng nhập tại đây.",
    signUpAsk = "Không có tài khoản? Đăng kí tại đây.",
    sun = "Trời nắng",
    clear = "Trời quang",
    profileAva = "Ảnh hồ sơ",
    warningHistory = "Lịch sử cảnh báo",
    changeAva = "Thay đổi ảnh đại diện",
    PicFrom = "Bạn muốn chọn ảnh từ đâu?",
    lib = "Thư viện",
    cam = "Máy ảnh",
    ava = "Ảnh đại diện",
    profile = "Hồ sơ cá nhân",
    newPass = "Mật khẩu mới",
    oldPass = "Mật khẩu cũ",
    errorPass = "Mật khẩu không đúng",
    updatePass = "Cập nhật mật khẩu mới",
    save = "Lưu",
    security = "Bảo mật",
    sysSetting = "Cài đặt hệ thống",
    themes = "Chế độ nền",
    current = "Hiện tại",
    interf = "Giao diện",
    selectThemes = "Chọn chế độ nền",
    Light = "Sáng",
    Dark = "Tối",
    Sys = "Hệ thống",
    presets = "Thiết lập chế độ",
    createPreset = "Tạo ngữ cảnh",
    editPreset = "Chỉnh sửa ngữ cảnh",
    deviceNameDefault = "Thiết bị",
    color = "Màu sắc",
    speed = "Tốc độ gió",
    brightness = "Độ sáng",
    osc = "Chế độ quay",
    track = "Theo dõi người dùng",
    saveSuccess = "Đã lưu thành công",
    enterPresetName = "Nhập tên ngữ cảnh (VD: Đi ngủ)",
    on = "Bật",
    off = "Tắt",
    addDevice = "Thêm thiết bị",
    addFan = "Thêm quạt",
    addLight = "Thêm đèn",
    addDeviceAsk = "Bạn muốn thêm thiết bị nào vào ",
    rename = "Đổi tên",
    popular = "Phổ biến",
    home = "Nhà cửa",
    weahther = "Thời tiết",
    activity = "Hoạt động",
    other = "Khác",
)

// Dữ liệu Tiếng Anh
val EnglishStrings = AppStrings(
    welcome = "Welcome home,",
    login = "Login",
    signUp = "Sign Up",
    fullName = "Full Name",
    username = "Username",
    password = "Password",
    temp = "Temperature",
    lit = "Lighting",
    devices = "Devices",
    devicesIn = "Devices in ",
    logout = "Logout",
    settings = "System Settings",
    changePass = "Change Password",
    language = "Language",
    room = "Rooms",
    roomKitchen = "Kitchen",
    roomLiving = "Living Room",
    roomBed = "Bedroom",
    roomBath = "Bathroom",
    Garden = "Garden",
    fan = "Fan",
    led = "LED",
    warning = "Security Alert!",
    loginAsk = "Already have an account? Log in here",
    signUpAsk = "Don’t have an account? Sign up here",
    sun = "Sunny",
    clear = "Clear Sky",
    profileAva = "Profile Avatar",
    warningHistory = "Warning History",
    changeAva = "Change avatar",
    PicFrom = "Where would you like to choose the photo from",
    lib = "Library",
    cam = "Camera",
    ava = "Avatar",
    profile = "Profile",
    newPass = "New password",
    oldPass = "Old password",
    errorPass = "Incorrect Password",
    updatePass = "Update new password",
    save = "Save",
    security = "Security",
    sysSetting = "System Setting",
    themes = "Themes",
    current = "Current",
    interf = "Interface",
    selectThemes = "Choose themes",
    Light = "Light",
    Dark = "Dark",
    Sys = "System",
    presets = "Presets",
    createPreset = "Create Preset",
    editPreset = "Edit Preset",
    deviceNameDefault = "Device",
    color = "Color",
    speed = "Fan Speed",
    brightness = "Brightness",
    osc = "Oscillation",
    track = "Tracking",
    saveSuccess = "Saved successfully",
    enterPresetName = "Preset Name (e.g. Sleep)",
    on = "On",
    off = "Off",
    addDevice = "Add Device",
    addFan = "Add fan",
    addLight = "Add LED",
    addDeviceAsk = "Which device would you like to add to ",
    rename = "Rename",
    popular = "Popular",
    home = "Home",
    weahther = "Weather",
    activity = "Activity",
    other = "Others",
    )